[package]
name = "djinn"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["cargo"] }
dotenv = "0.15.0"
json = "0.12.4"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde_json = "1.0.128"
tokio = "1.40.0"
